/**
 * Integration smoke for `extractPdfMetadata`.
 *
 * Why this test exists:
 *   - Issue #3 acceptance: real PDF bytes → real `loadPdfDocument()`
 *     call → metadata extracted. No fake-worker fallback, no
 *     mock for `getDocument`.
 *   - The MVP cannot ship with a silent "if pdf.js fails to load,
 *     pretend it worked" path. A vitest that exercises the actual
 *     bundled worker is the cheapest way to catch that.
 *
 * Why `pdf-lib` to generate the fixture:
 *   - pdf-lib is MIT, devDep-only, no runtime footprint. It
 *     produces a fully valid PDF (xref offsets computed
 *     correctly, no hand-rolled byte stream).
 *   - Alternative: hand-rolled minimal PDF. Rejected because
 *     xref offsets are byte-count-dependent and easy to get
 *     wrong; pdf-lib removes that risk for one cheap dependency.
 *
 * What we verify:
 *   1. `extractPdfMetadata` reads the page count from a real
 *      2-page PDF generated by pdf-lib.
 *   2. The pdf.js parser (legacy build, main thread) actually
 *      parses the bytes end-to-end — proven by the fact that
 *      a real PDF yields the right page count and /Info fields.
 *   3. `PdfInvalidError` (our boundary class) is thrown for
 *      non-PDF bytes — the library layer can discriminate by
 *      `instanceof` without inspecting pdf.js internals.
 *   4. A bad-import followed by a good-import still works —
 *      end-to-end check that `loadPdfDocument()` cleans up
 *      its loading task on rejection (no leaked worker /
 *      stalled state).
 *
 * Note on what this smoke does NOT cover:
 *   - The browser's bundled `pdf.worker.min.mjs` being
 *     successfully loaded as a Worker module. Vitest here uses
 *     `pdfjs-dist/legacy/build/pdf.mjs` (main-thread parse);
 *     it proves pdf.js's *parser*, not that the worker asset
 *     ships correctly. The worker-side verification lives in
 *     `scripts/smoke-import.mjs` — run once against
 *     `bun run preview` and the result is recorded in PR #24.
 */

import { PDFDocument } from 'pdf-lib';
import { describe, expect, it } from 'vitest';
import { PdfInvalidError } from './pdf-errors.ts';
import { extractPdfMetadata, pdfMetadataToSourceMetadata } from './pdf-metadata.ts';

async function makeTwoPagePdfBytes(): Promise<Uint8Array> {
	const pdf = await PDFDocument.create();
	pdf.addPage(); // page 1
	pdf.addPage(); // page 2
	pdf.setTitle('Smoke Test Title');
	pdf.setAuthor('Smoke Test Author');
	return await pdf.save();
}

/** pdf-lib's `save()` returns `Uint8Array<ArrayBufferLike>` whose
 *  TypeScript type is technically not assignable to `BlobPart`
 *  (`ArrayBufferLike` includes `SharedArrayBuffer`). In practice
 *  under Node it is plain `ArrayBuffer`. We cast at the boundary
 *  to satisfy the type checker without copying or wrapping.
 *
 *  Why we pass the Uint8Array view, not the underlying buffer:
 *  happy-dom's `Blob` constructor handles a `Uint8Array` view
 *  correctly but loses byte data when given an `ArrayBuffer`
 *  directly — pdf.js's legacy build then rejects the resulting
 *  bytes with "Invalid PDF structure". Passing the view works. */
function bytesToBlob(bytes: Uint8Array): Blob {
	return new Blob([bytes as unknown as ArrayBuffer], { type: 'application/pdf' });
}

describe('extractPdfMetadata (real PDF integration smoke)', () => {
	it('reads pageCount from a 2-page PDF', async () => {
		const bytes = await makeTwoPagePdfBytes();
		const blob = bytesToBlob(bytes);

		const meta = await extractPdfMetadata(blob);

		expect(meta.pageCount).toBe(2);
	});

	it('reads /Info Title and Author', async () => {
		const bytes = await makeTwoPagePdfBytes();
		const blob = bytesToBlob(bytes);

		const meta = await extractPdfMetadata(blob);

		expect(meta.title).toBe('Smoke Test Title');
		expect(meta.author).toBe('Smoke Test Author');
	});

	it('supports two sequential imports of the same blob', async () => {
		// Renamed from "releases the document proxy after the
		// call" — the original test admitted it could not prove
		// release. This version only proves that two calls in
		// a row succeed (a leaked proxy might or might not
		// fail this; we accept the looser guarantee).
		const bytes = await makeTwoPagePdfBytes();
		const blob = bytesToBlob(bytes);

		const meta = await extractPdfMetadata(blob);
		const meta2 = await extractPdfMetadata(blob);

		expect(meta.pageCount).toBe(2);
		expect(meta2.pageCount).toBe(2);
	});

	it('throws PdfInvalidError for non-PDF bytes (boundary class, not a raw pdf.js exception)', async () => {
		const blob = new Blob(['this is plain text, not a pdf'], {
			type: 'application/pdf',
		});

		await expect(extractPdfMetadata(blob)).rejects.toBeInstanceOf(PdfInvalidError);
	});

	it('recovers from a bad-PDF load — next valid import still works', async () => {
		// End-to-end test of `loadPdfDocument`'s failure-cleanup
		// contract (see `pdf-document.ts`): if the loading task
		// rejects, `loadingTask.destroy()` is awaited before
		// rethrow. A leaked loading task would stall subsequent
		// imports in the same session; here we prove that a bad
		// import does NOT corrupt state for the next one.
		const badBlob = new Blob(['not a pdf'], { type: 'application/pdf' });
		await expect(extractPdfMetadata(badBlob)).rejects.toBeInstanceOf(PdfInvalidError);

		const goodBytes = await makeTwoPagePdfBytes();
		const goodBlob = bytesToBlob(goodBytes);
		const meta = await extractPdfMetadata(goodBlob);

		expect(meta.pageCount).toBe(2);
	});
});

describe('pdfMetadataToSourceMetadata (full forward)', () => {
	it('mirrors pageCount', () => {
		expect(pdfMetadataToSourceMetadata({ pageCount: 12 }).pageCount).toBe(12);
	});

	it('forwards title and author when present', () => {
		const out = pdfMetadataToSourceMetadata({
			pageCount: 3,
			title: '雪国',
			author: '川端康成',
		});
		expect(out.title).toBe('雪国');
		expect(out.author).toBe('川端康成');
	});

	it('omits absent keys (does not set them to undefined)', () => {
		// `exactOptionalPropertyTypes` rejects explicit `undefined`,
		// so the helper must drop absent fields entirely — pin that.
		const out = pdfMetadataToSourceMetadata({ pageCount: 1 });
		expect('title' in out).toBe(false);
		expect('author' in out).toBe(false);
	});
});
